# Generated by Django 3.0.2 on 2020-01-16 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEstudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNivel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedulaActor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=10)),
                ('nivelEstudios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.NivelEstudios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
