# Generated by Django 3.0.2 on 2020-01-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startelpApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblActividadComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAct', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tblCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tblCiudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tblProvincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProvincia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoFinanciamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFinanc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tblStartup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='tblSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSector', models.CharField(max_length=50)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.tblCiudad')),
            ],
        ),
        migrations.CreateModel(
            name='tblNegocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNegocio', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagenNegocio', models.ImageField(upload_to='uploads/')),
                ('address', models.CharField(max_length=100)),
                ('montoRequerido', models.FloatField()),
                ('fechaCreacion', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.tblCategoria')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.tblSector')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.tblStartup')),
            ],
        ),
        migrations.CreateModel(
            name='tblInversionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('experienciaInversion', models.BooleanField()),
                ('financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.tipoFinanciamiento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='tblInteresInversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.tblCategoria')),
                ('inversionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.tblInversionista')),
            ],
        ),
        migrations.CreateModel(
            name='tblContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaContacto', models.DateTimeField()),
                ('inversionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.tblInversionista')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.tblNegocio')),
            ],
        ),
        migrations.AddField(
            model_name='tblciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.tblProvincia'),
        ),
    ]
