# Generated by Django 2.2.9 on 2020-02-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startelpApp', '0003_auto_20200204_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinversionista',
            name='financiamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_financiamiento', to='startelpApp.tipoFinanciamiento'),
        ),
        migrations.CreateModel(
            name='tblFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_favorito', models.CharField(max_length=25)),
                ('inversionista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startelpApp.tblInversionista')),
                ('lista_negocios', models.ManyToManyField(to='startelpApp.tblNegocio')),
            ],
        ),
    ]
